# Generated by Django 4.2.1 on 2024-08-01 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HighlightLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_user', models.CharField(max_length=255, null=True)),
                ('report_owner', models.CharField(max_length=255)),
                ('realm', models.CharField(max_length=255)),
                ('highlight_type', models.CharField(max_length=255)),
                ('guild_name', models.CharField(max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('creation_status', models.CharField(choices=[('CREATED', 'Created'), ('FAILED', 'Failed'), ('REFUSED', 'Refused')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HighlightDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=255)),
                ('fight_id', models.IntegerField(null=True)),
                ('player_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('img', models.CharField(blank=True, max_length=255)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.highlight')),
            ],
        ),
    ]
