# Generated by Django 4.2.1 on 2024-08-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=255)),
                ('player_name', models.CharField(max_length=255)),
                ('total_legendary_parses', models.IntegerField(default=0)),
                ('best_legendary_parse', models.FloatField(blank=True, null=True)),
                ('best_rank_avg_dps_parses', models.FloatField(blank=True, null=True)),
                ('best_ilvl_avg_dps_parses', models.FloatField(blank=True, null=True)),
                ('best_rank_avg_hps_parses', models.FloatField(blank=True, null=True)),
                ('best_ilvl_avg_hps_parses', models.FloatField(blank=True, null=True)),
                ('fight_id', models.IntegerField(blank=True, null=True)),
                ('encounter_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dps_rank_percent', models.FloatField(blank=True, null=True)),
                ('dps_bracket_percent', models.FloatField(blank=True, null=True)),
                ('hps_rank_percent', models.FloatField(blank=True, null=True)),
                ('hps_bracket_percent', models.FloatField(blank=True, null=True)),
                ('dtps', models.FloatField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
