# Generated by Django 4.2.1 on 2024-08-01 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighlightLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_user', models.CharField(max_length=255, null=True)),
                ('report_owner', models.CharField(max_length=255)),
                ('realm', models.CharField(max_length=255)),
                ('highlight_type', models.CharField(max_length=255)),
                ('guild_name', models.CharField(max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('creation_status', models.CharField(choices=[('CREATED', 'Created'), ('FAILED', 'Failed'), ('REFUSED', 'Refused')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='highlightdetails',
            name='fight_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='highlightdetails',
            name='img',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
