# Generated by Django 4.2.1 on 2024-08-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_individualhighlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlightdetails',
            name='difficulty',
            field=models.IntegerField(blank=True, choices=[(1, 'LFR'), (2, 'Flex'), (3, 'Normal'), (4, 'Heroic'), (5, 'Mythic')], null=True),
        ),
        migrations.AddField(
            model_name='highlightdetails',
            name='zone_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='individualhighlight',
            name='difficulty',
            field=models.IntegerField(blank=True, choices=[(1, 'LFR'), (2, 'Flex'), (3, 'Normal'), (4, 'Heroic'), (5, 'Mythic')], null=True),
        ),
    ]
