# Generated by Django 4.2.1 on 2024-08-09 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_highlightdetails_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlightdetails',
            name='highlight_value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
