# Generated by Django 4.2.1 on 2024-08-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_highlightdetails_highlight_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlightdetails',
            name='player_class',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualhighlight',
            name='player_class',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
