# Generated by Django 4.2.1 on 2024-09-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_highlightdetails_player_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlightdetails',
            name='boss_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
