# Generated by Django 4.2.1 on 2024-09-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_highlightdetails_boss_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('zone_name', models.CharField(blank=True, max_length=255, null=True)),
                ('expansion_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
