# Generated by Django 4.2.1 on 2024-09-26 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_boss'),
    ]

    operations = [
        migrations.CreateModel(
            name='BossTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('translated_name', models.CharField(max_length=255)),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='api.boss')),
            ],
            options={
                'unique_together': {('boss', 'language_code')},
            },
        ),
    ]
